#docker-compose up -d
version: "3.7"

services:
  mysqldb:
    image: mysql:8.0.28
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.1
    container_name: mysqladmin
    environment:
      PMA_HOST: mysqldb
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - 8000:80
  
  mvn:
    image: maven:3.8.5-openjdk-8-slim
    container_name: jdkmvn
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_DATABASE: db_example
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      SERVER_PORT: 8080
    working_dir: /app
    volumes:
      - $HOME/uzrnem/note-app-spring-boot:/app
      - $HOME/.m2:/root/.m2
    command: mvn spring-boot:run #tail -f /dev/null
    ports:
      - 8080:8080
