#docker-compose up -d
version: "3.7"

services:
  mvn:
    image: maven:3.9.2-ibmjava-8
    container_name: node-app
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_DATABASE: db_example
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      SERVER_PORT: 8080
    working_dir: /app
    volumes:
      - $HOME/uzrnem/note-app-spring-boot:/app
      - $HOME/uzrnem/dependencies/.m2:/root/.m2
    command: tail -f /dev/null #mvn spring-boot:run #
    ports:
      - 8080:8080
    networks:
      - docker-compose-files_mysql

networks:
  docker-compose-files_mysql:
    external: true