logging:
  level:
    .: error
    org.springframework: ERROR
    com.example.demo: INFO

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    # enabled: false
  api-docs:
    path: /api-docs
    # enabled: false

server:
  port: ${SERVER_PORT:8080}

spring:
  profiles:
    active: default
  jwt:
    secret: bhagyesh
    exp_time: 3600
  main:
    banner-mode: off

---
spring:
  profiles: default
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:mysqldb}:3306/${MYSQL_DATABASE:db_example}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    validationQuery: SELECT 1

---
spring:
  profiles: test
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    driverClassName: org.h2.Driver
